---
title: "Example analysis"
output: html_vignette
---


```{r library}
library(laminr)
db <- connect()
db$track("H6pK9lWJeie00002", path = "example_analysis.Rmd")
```

## Download a dataset from CELLxGENE

Fetch dataset related to renal cell carcinoma ([`7dVluLROpalzEh8mNyxk`](https://lamin.ai/laminlabs/cellxgene/artifact/7dVluLROpalzEh8mNyxk)).

```{r connect-cellxgene}
cellxgene <- connect("laminlabs/cellxgene")
adata <- cellxgene$Artifact$get("7dVluLROpalzEh8mNyxk")$load()
adata
```

## Marker analysis with Seurat

Create a Seurat object

```{r create-seurat}
library(Seurat)

seurat <- CreateSeuratObject(
  counts = as(Matrix::t(adata$X), "CsparseMatrix"),
  meta.data = adata$obs,
)
Idents(seurat) <- "cell_type"
```

Normalise the data

```{r normalise}
seurat <- NormalizeData(seurat)
```

Test for marker genes

```{r find-markers}
markers <- FindAllMarkers(
  seurat,
  features = Features(seurat)
)

knitr::kable(markers)
```

Plot the marker genes

```{r plot-marker}
library(tidyverse)
marker_sel <- markers %>%
  group_by(gene) %>%
  arrange(p_val) %>%
  slice(1) %>%
  ungroup()

DotPlot(seurat, features = marker_sel$gene[1:10]) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

## Store for later use

```{r save-results}
db$Artifact$from_df(
  markers,
  description = "Marker genes for renal cell carcinoma dataset"
)$save()

seurat_path <- tempfile(fileext = ".rds")
saveRDS(seurat, seurat_path)
db$Artifact$from_path(
  seurat_path,
  description = "Seurat object for renal cell carcinoma dataset"
)$save()
```

# Stop tracking

When we are done we end the tracking run.

```{r finish}
db$finish()
```
